_PIRATE_WORDS = {
    "hello": "ahoy",
    "hello.": "ahoy.",
    "hello,": "ahoy,",
    "hello!": "ahoy!",
    "hello?": "ahoy?",
    "heya": "ahoy",
    "heya.": "ahoy.",
    "heya,": "ahoy,",
    "heya!": "ahoy!",
    "heya?": "ahoy?",
    "hey": "ahoy",
    "hey.": "ahoy.",
    "hey,": "ahoy,",
    "hey!": "ahoy!",
    "hey?": "ahoy?",
    "hi": "arrr",
    "hi!": "arrr!",
    "hi,": "arrr,",
    "hi.": "arrr.",
    "hi?": "arrr?",
    "my": "me",
    "friend": "m'hearty",
    "friend!": "m'hearty!",
    "friend,": "m'hearty,",
    "friend.": "m'hearty.",
    "friend?": "m'hearty?",
    "boy": "laddy",
    "boy.": "laddy.",
    "boy!": "laddy!",
    "boy,": "laddy,",
    "boy?": "laddy?",
    "girl": "lassie",
    "girl,": "lassie,",
    "girl!": "lassie!",
    "girl.": "lassie.",
    "girl?": "lassie?",
    "sir": "matey",
    "sir.": "matey.",
    "sir!": "matey!",
    "sir,": "matey,",
    "sir?": "matey?",
    "guys": "matey",
    "guys.": "matey.",
    "guys!": "matey!",
    "guys,": "matey,",
    "guy?": "matey?",
    "miss": "proud beauty",
    "miss.": "proud beauty.",
    "miss!": "proud beauty!",
    "miss,": "proud beauty,",
    "miss?": "proud beauty?",
    "stranger": "scurvy dog",
    "stranger.": "scurvy dog.",
    "stranger!": "scurvy dog!",
    "stranger,": "scurvy dog,",
    "stranger?": "scurvy dog?",
    "boss": "foul blaggart",
    "boss!": "foul blaggart!",
    "boss.": "foul blaggart.",
    "boss,": "foul blaggart,",
    "boss?": "foul blaggart?",
    "where": "whar",
    "where?": "whar?",
    "is": "be",
    "is?": "be?",
    "the": "th'",
    "you": "ye",
    "you?": "ye?",
    "you.": "ye.",
    "you!": "ye!",
    "you,": "ye,",
    "old": "barnacle covered",
    "old!": "barnacle covered!",
    "old,": "barnacle covered,",
    "old?": "barnacle covered?",
    "old.": "barnacle covered.",
    "happy": "grog-filled",
    "happy.": "grog-filled.",
    "happy!": "grog-filled!",
    "happy,": "grog-filled,",
    "happy?": "grog-filled?",
    "nearby": "broadside",
    "nearby!": "broadside!",
    "nearby?": "broadside?",
    "nearby.": "broadside.",
    "nearby,": "broadside,",
    "bathroom": "head",
    "bathroom!": "head!",
    "bathroom.": "head.",
    "bathroom,": "head,",
    "bathroom?": "head?",
    "kitchen": "galley",
    "kitchen!": "galley!",
    "kitchen.": "galley.",
    "kitchen,": "galley,",
    "kitchen?": "galley?",
    "pub": "fleabag inn",
    "pub?": "fleabag inn?",
    "pub.": "fleabag inn.",
    "pub!": "fleabag inn!",
    "pub,": "fleabag inn,",
    "stop": "avast",
    "stop,": "avast,",
    "stop.": "avast.",
    "stop?": "avast?",
    "stop!": "avast!",
    "yes": "aye",
    "yes?": "aye?",
    "yes,": "aye,",
    "yes.": "aye.",
    "yes!": "aye!",
    "no": "nay",
    "no,": "nay,",
    "no?": "nay?",
    "no.": "nay.",
    "no!": "nay!",
    "yay": "yo-ho-ho",
    "yay?": "yo-ho-ho?",
    "yay,": "yo-ho-ho,",
    "yay.": "yo-ho-ho.",
    "yay!": "yo-ho-ho!",
    "money": "doubloons",
    "money,": "doubloons,",
    "money.": "doubloons.",
    "money!": "doubloons!",
    "money?": "doubloons?",
    "treasure": "booty",
    "treasure!": "booty!",
    "treasure.": "booty.",
    "treasure?": "booty?",
    "treasure,": "booty,",
    "take": "pillage",
    "take!": "pillage!",
    "take.": "pillage.",
    "take?": "pillage?",
    "take,": "pillage,",
    "drink": "grog",
    "drink.": "grog.",
    "drink?": "grog?",
    "drink,": "grog,",
    "drink!": "grog!",
    "idiot": "scallywag",
    "idiot!": "scallywag!",
    "idiot?": "scallywag?",
    "idiot.": "scallywag.",
    "idiot,": "scallywag,",
    "sea": "briney deep",
    "sea!": "briney deep!",
    "sea,": "briney deep,",
    "sea.": "briney deep.",
    "sea?": "briney deep?",
    "song": "shanty",
    "song!": "shanty!",
    "song?": "shanty?",
    "song,": "shanty,",
    "song.": "shanty.",
    "drunk": "three sheets to the wind",
    "drunk!": "three sheets to the wind?",
    "drunk?": "three sheets to the wind!",
    "drunk.": "three sheets to the wind.",
    "drunk,": "three sheets to the wind,",
    "talk": "parley",
    "talk!": "parley!",
    "talk?": "parley?",
    "talk.": "parley.",
    "talk,": "parley,",
    "fail": "scupper",
    "fail!": "scupper!",
    "fail?": "scupper?",
    "fail.": "scupper.",
    "fail,": "scupper,",
    "quickly": "smartly",
    "quickly.": "smartly.",
    "quickly,": "smartly,",
    "quickly!": "smartly!",
    "quickly?": "smartly?",
}


#: A list of Pirate phrases to randomly insert before or after sentences.
_PIRATE_PHRASES = [
    "batten down the hatches!",
    "splice the mainbrace!",
    "thar she blows!",
    "arrr!",
    "weigh anchor and hoist the mizzen!",
    "savvy?",
    "dead men tell no tales.",
    "cleave him to the brisket!",
    "blimey!",
    "blow me down!",
    "avast ye!",
    "yo ho ho.",
    "shiver me timbers!",
    "blisterin' barnacles!",
    "ye flounderin' nincompoop.",
    "thundering typhoons!",
]

# Walk the plank
_WALK_THE_PLANK = [
'''```
 O
/|\\
/ \\______________
              ,
______________)\\_____________
      (\\_.-'    a`-.
      (/~~``\\``(/~^^`
```''',
'''```
     O
    /|\\
____/ \\__________
              ,
______________)\\_____________
      (\\_.-'    a`-.
      (/~~``\\``(/~^^`
```''',
'''```
          O
         /|\\
_________/ \\_____
              ,
______________)\\_____________
      (\\_.-'    a`-.
      (/~~``\\``(/~^^`
```''',
'''```
              O
             /|\\
_____________/ \\_
              ,
______________)\\_____________
      (\\_.-'    a`-.
      (/~~``\\``(/~^^`
```''',
'''```

              ,     Thanks for the meal ;)
______________)\\______/______
      (\\_.-'    a`-. /
      (/~~``\\``(/~^^`
```''',
]